blank_issues_enabled: true
contact_links:
  - name: Preguntar en el grupo de WhatsApp
    url: https://chat.whatsapp.com/Bj1KKgjcLue2FOVuX8osmq
    about: Para dudas rápidas, el grupo responde más rápido que un issue.
